# Generated by Django 4.1.5 on 2023-06-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course_study',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
