# Generated by Django 4.1.5 on 2023-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0002_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
