# Generated by Django 4.1.5 on 2023-06-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0002_teacher_course_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='confirm_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
