# Generated by Django 4.1.5 on 2023-06-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0004_alter_teacher_address_alter_teacher_mobile_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='country_name',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='confirm_password',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='postCode',
            new_name='post_code',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='course_study',
            new_name='skills',
        ),
    ]
