# Generated by Django 4.1.5 on 2023-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0005_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=15, null=True),
        ),
    ]
